server:
  port: 8082

spring:
  application:
    name: project-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/project-tracker?useSSL=false # Connection parameter of database
    username: Bhavesh # Username of the database
    password: # Password of the database
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: project-tracker-hikari
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop  # Use 'update', 'create', or 'validate' as needed
    show-sql: true      # Enables SQL query logging
